.TH "/home/djordje/Desktop/actuator-sensor-board/src/usart0.h" 3 "Fri Mar 16 2018" "actuator-sensor-board" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/djordje/Desktop/actuator-sensor-board/src/usart0.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBUSART0_init\fP (uint32_t baud)"
.br
.ti -1c
.RI "void \fBUSART0_transmit\fP (unsigned char data)"
.br
.ti -1c
.RI "unsigned char \fBUSART0_receive\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void USART0_init (uint32_t baud)"
Uart0 configuring for communication with dynamixel ax-12a servo motor\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdesired\fP baud rate, double speed mode 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for actuator-sensor-board from the source code\&.
